"""Database schema.

Three tables:
  api_spec       one row per (api_id, major_version), with the raw spec as JSONB
  data_product   one row per data product, with the raw contract as JSONB
  chunk          the searchable units: API overviews, endpoints, data product
                 overviews and fields. Filter columns are denormalised onto the
                 chunk so a search is a single-table query.

The `tsv` column is generated by Postgres; the HNSW index serves cosine search.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    ARRAY,
    Boolean,
    CheckConstraint,
    Computed,
    Date,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

EMBEDDING_DIM = 384  # must match Settings.embedding_dim; changing it needs a migration


class Base(DeclarativeBase):
    pass


class ApiSpec(Base):
    __tablename__ = "api_spec"
    __table_args__ = (UniqueConstraint("api_id", "major_version", name="uq_api_spec_version"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    api_id: Mapped[str] = mapped_column(String(120), index=True)
    major_version: Mapped[int] = mapped_column(Integer)
    version: Mapped[str] = mapped_column(String(40))
    title: Mapped[str] = mapped_column(String(200))
    description: Mapped[str | None] = mapped_column(Text)
    domain: Mapped[str] = mapped_column(String(40), index=True)
    owner_team: Mapped[str] = mapped_column(String(120))
    countries: Mapped[list[str]] = mapped_column(ARRAY(String(2)))
    audience: Mapped[str] = mapped_column(String(40))
    data_classification: Mapped[str | None] = mapped_column(String(20))
    lifecycle_status: Mapped[str] = mapped_column(String(20))
    sunset: Mapped[date | None] = mapped_column(Date)
    replacement: Mapped[str | None] = mapped_column(String(160))
    metadata_provenance: Mapped[dict[str, str]] = mapped_column(JSONB)
    source_path: Mapped[str] = mapped_column(String(300))
    content_hash: Mapped[str] = mapped_column(String(64))
    raw: Mapped[dict[str, Any]] = mapped_column(JSONB)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class DataProductRow(Base):
    __tablename__ = "data_product"

    id: Mapped[int] = mapped_column(primary_key=True)
    product_id: Mapped[str] = mapped_column(String(120), unique=True)
    name: Mapped[str] = mapped_column(String(200))
    version: Mapped[str] = mapped_column(String(40))
    status: Mapped[str] = mapped_column(String(20))
    domain: Mapped[str] = mapped_column(String(40), index=True)
    owner_team: Mapped[str] = mapped_column(String(120))
    countries: Mapped[list[str]] = mapped_column(ARRAY(String(2)))
    pii_classification: Mapped[str] = mapped_column(String(20))
    description: Mapped[str] = mapped_column(Text)
    source_path: Mapped[str] = mapped_column(String(300))
    content_hash: Mapped[str] = mapped_column(String(64))
    raw: Mapped[dict[str, Any]] = mapped_column(JSONB)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )


class Chunk(Base):
    __tablename__ = "chunk"
    __table_args__ = (
        CheckConstraint("(api_spec_id IS NULL) <> (data_product_id IS NULL)", name="ck_chunk_one_parent"),
        Index("ix_chunk_tsv", "tsv", postgresql_using="gin"),
        Index("ix_chunk_countries", "countries", postgresql_using="gin"),
        Index(
            "ix_chunk_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    # Stable natural key, e.g. "api:claims-api:2:GET /claims/{claimId}" - drives upserts.
    chunk_key: Mapped[str] = mapped_column(String(400), unique=True)
    kind: Mapped[str] = mapped_column(String(30), index=True)  # api|endpoint|data_product|field
    api_spec_id: Mapped[int | None] = mapped_column(ForeignKey("api_spec.id", ondelete="CASCADE"), index=True)
    data_product_id: Mapped[int | None] = mapped_column(ForeignKey("data_product.id", ondelete="CASCADE"), index=True)

    # Denormalised identity and filters.
    asset_type: Mapped[str] = mapped_column(String(20))  # api | data_product
    asset_id: Mapped[str] = mapped_column(String(120))
    major_version: Mapped[int | None] = mapped_column(Integer)
    domain: Mapped[str] = mapped_column(String(40), index=True)
    countries: Mapped[list[str]] = mapped_column(ARRAY(String(2)))
    deprecated: Mapped[bool] = mapped_column(Boolean, default=False)
    pii_level: Mapped[str | None] = mapped_column(String(20))
    method: Mapped[str | None] = mapped_column(String(10))
    path: Mapped[str | None] = mapped_column(String(300))
    field_name: Mapped[str | None] = mapped_column(String(120))

    title: Mapped[str] = mapped_column(String(400))
    body: Mapped[str] = mapped_column(Text)
    content_hash: Mapped[str] = mapped_column(String(64))
    embedding: Mapped[list[float] | None] = mapped_column(Vector(EMBEDDING_DIM))
    embedding_model: Mapped[str | None] = mapped_column(String(120))
    tsv: Mapped[Any] = mapped_column(
        TSVECTOR,
        Computed("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(body, ''))", persisted=True),
    )


class AccessRequest(Base):
    """A request for access to an API or data product. Created pending; only a human decides."""

    __tablename__ = "access_request"
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending_approval', 'approved', 'rejected', 'withdrawn')", name="ck_access_request_status"
        ),
        CheckConstraint("(status = 'pending_approval') = (decided_by IS NULL)", name="ck_access_request_decided_by"),
        CheckConstraint("decided_by IS NULL OR decided_by <> requester", name="ck_access_request_four_eyes"),
        Index(
            "uq_access_request_open",
            "requester",
            "asset_type",
            "asset_id",
            text("coalesce(major_version, 0)"),
            "purpose",
            unique=True,
            postgresql_where=text("status = 'pending_approval'"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    requester: Mapped[str] = mapped_column(String(200), index=True)
    asset_type: Mapped[str] = mapped_column(String(20))
    asset_id: Mapped[str] = mapped_column(String(120))
    major_version: Mapped[int | None] = mapped_column(Integer)
    purpose: Mapped[str] = mapped_column(String(120))
    justification: Mapped[str] = mapped_column(Text)
    requested_scope: Mapped[str] = mapped_column(String(200))
    approval_route: Mapped[str] = mapped_column(String(60))
    approvers: Mapped[list[str]] = mapped_column(ARRAY(String(120)))
    status: Mapped[str] = mapped_column(String(30))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    decided_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    decided_by: Mapped[str | None] = mapped_column(String(200))
    decision_note: Mapped[str | None] = mapped_column(Text)
