"""Generate the synthetic OpenAPI catalog into catalog/apis/.

Usage (from the project root):
    uv run python -m scripts.catalog_gen          # (re)write the YAML files
    uv run python -m scripts.catalog_gen --check  # fail if committed files drift from the generator
"""

from __future__ import annotations

import argparse
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

import yaml

from . import claims, customer, documents, fraud, partner, payments, policy, quotes

ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "catalog" / "apis"
HEADER = "# GENERATED by scripts/catalog_gen - synthetic data for the fictional Nordlys Insurance.\n"

ALL_SPECS: list[tuple[str, Callable[[], dict[str, Any]]]] = [
    *policy.SPECS,
    *claims.SPECS,
    *quotes.SPECS,
    *customer.SPECS,
    *partner.SPECS,
    *payments.SPECS,
    *documents.SPECS,
    *fraud.SPECS,
]


class _Dumper(yaml.SafeDumper):
    """Readable YAML: block style for multi-line strings, no anchors/aliases."""

    def ignore_aliases(self, data: Any) -> bool:
        return True


def _str_presenter(dumper: yaml.SafeDumper, data: str) -> yaml.ScalarNode:
    if "\n" in data:
        return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")
    return dumper.represent_scalar("tag:yaml.org,2002:str", data)


_Dumper.add_representer(str, _str_presenter)


def render(doc: dict[str, Any]) -> str:
    return HEADER + yaml.dump(doc, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=110)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify instead of writing")
    args = parser.parse_args()

    drift: list[str] = []
    expected = set()
    for rel_path, build in ALL_SPECS:
        target = OUT_DIR / rel_path
        expected.add(target)
        content = render(build())
        if args.check:
            if not target.exists() or target.read_text(encoding="utf-8") != content:
                drift.append(rel_path)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")

    stray = sorted(str(p.relative_to(OUT_DIR)) for p in OUT_DIR.rglob("*.yaml") if p not in expected)
    if args.check:
        if drift or stray:
            print(f"Catalog drift: changed={drift} unexpected={stray}", file=sys.stderr)
            return 1
        print(f"OK: {len(ALL_SPECS)} specs match the generator")
    else:
        print(f"Wrote {len(ALL_SPECS)} specs to {OUT_DIR.relative_to(ROOT)}")
        if stray:
            print(f"Warning: files not produced by the generator: {stray}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
